# Generated by Django 4.1.5 on 2023-01-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='img',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
